### PR TITLE
Email Validation added

### LINKED ISSUE #1119: No check present for valid email address
#### Nature of issue?

- Found a bug

#### Details about the bug: 
In the reset password route, there is no check if a valid email address is entered or not.
Capture

- Web browser and version: Chrome
- Operating System: Windows
- Steps to reproduce this bug:
 1) Visit reset password route
 2) Enter anything and check.

I would like to work on this.

### PR DESCRIPTION
**Pull request by plxity**
I have verified that this pull request:
Fixes #1119 
* [x] has no linting errors (`npm run lint`)
* [x] is from a uniquely-named feature branch and has been rebased on top of the latest master. (If I was asked to make more changes, I have made sure to rebase onto master then too)
* [x] is descriptively named and links to an issue number, i.e. `Fixes #123`

@catarak Please review it :)

### CODE REVIEW

File: client/modules/User/pages/ResetPasswordView.jsx [hunk 1]
```diff
@@ -83,7 +84,11 @@ function mapDispatchToProps(dispatch) {
 function validate(formProps) {
   const errors = {};
   if (!formProps.email) {
-    errors.email = 'Please enter an email';
+    errors.email = 'Please enter an email.';
+  } else if (
+    // eslint-disable-next-line max-len
+    !formProps.email.match(/^(([^<>()[\]\\.,;:\s@"]+(\.[^<>()[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/i)) {
```
Comment (catarak) [inline client/modules/User/pages/ResetPasswordView.jsx]: there's a file called `client/utils/reduxFormUtils.js` that has validation functions, including a regex to validate an email address. i would put a function in there and use that regex!

**Comment by catarak** [comment]
thanks for working on this issue!

File: client/modules/User/pages/ResetPasswordView.jsx (hunk 1 above)
Comment (plxity) [reply client/modules/User/pages/ResetPasswordView.jsx]: @catarak Okay, I will use that for file functions for validations.

**Comment by plxity** [comment]
@catarak Please review it :)

File: client/utils/reduxFormUtils.js [hunk 2]
```diff
@@ -79,3 +79,14 @@ export function validateSignup(formProps) {
 
   return errors;
 }
+export function validateResetPassword(formProps) {
+  const errors = {};
+  if (!formProps.email) {
+    errors.email = 'Please enter an email.';
+  } else if (
+    // eslint-disable-next-line max-len
+    !formProps.email.match(/^(([^<>()[\]\\.,;:\s@"]+(\.[^<>()[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/i)) {
```
Comment (catarak) [inline client/utils/reduxFormUtils.js]: rather than copying and pasting this regex twice, could you put it in a constant variable?

File: client/utils/reduxFormUtils.js [hunk 3]
```diff
@@ -15,6 +15,9 @@ export const domOnlyProps = ({
   ...domProps }) => domProps;
 /* eslint-enable */
 
+// eslint-disable-next-line max-len
+const EmailRegex = /^(([^<>()[\]\\.,;:\s@"]+(\.[^<>()[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/i;
```
Comment (catarak) [inline client/utils/reduxFormUtils.js]: this is a nit-picky personal style thing, but i prefer constants to be all uppercase (i.e. EMAIL_REGEX).

Comment (plxity) [reply client/utils/reduxFormUtils.js]: @catarak Done changes :)

Comment (catarak) [reply client/utils/reduxFormUtils.js]: 😸 thanks for humoring me

Comment (plxity) [reply client/utils/reduxFormUtils.js]: @catarak Can it be merged now? 😄

**Comment by catarak** [comment]
this works great. merging now!
