### PR TITLE
Edits to clarify the "share" modal - fixes #3567

### LINKED ISSUE #3567: Adding "Mode" to the text in the Share Modal
### p5.js version

Web Editor version 1.11.8

### What is your operating system?

MacOS

### Web browser and version

Chrome 137.0.7151.120 & Firefox 141.0 (aarch64)

### Actual Behavior

We (@team-epk & @kanishawilliams) were alerted to this issue during the Hands-On Activity included as part of the Open Source Software Contributor workshop hosted by Rachel Lim. The issue was documented [here](https://github.com/processing/p5.js-web-editor/wiki/Introduction-to-Open-Source-Contribution:-Hands%E2%80%90On-Issues-Activity). We suggest updating the text in the Share Modal to be more clear for users in terms of share options available for their sketch. We think this provides more clarity & context for the output the user selects. Below, please find the current text followed by "becomes" and our suggested edit:

**Suggested Changes**
- "Embed" becomes "Embed sketch"
- "Fullscreen" becomes "Share sketch as view-only"
- "Edit" becomes "Share sketch and allow editing"

### Expected Behavior

Once the changes are made, the labels in the Share Modal are more beginner-friendly.

### Steps to reproduce

1. Open Share Modal
2. Review sharing options

### PR DESCRIPTION
**Pull request by team-epk**
Fixes #3567 
Changes:
Slight adjustments to the Share modal text:

-     "Embed" becomes "Embed sketch"
-     "Fullscreen" becomes "Share sketch as view-only"
-     "Edit" becomes "Share sketch and allow editing"

I have verified that this pull request:

* [ x ] has no linting errors (`npm run lint`)
* [ x ] has no test errors (`npm run test`)
* [ x ] is from a uniquely-named feature branch and is up to date with the  `develop` branch.
* [ x ] is descriptively named and links to an issue number, i.e. `Fixes #123`

### CODE REVIEW

**Comment by team-epk** [comment]
[@freaug ](https://github.com/freaug) should get a fair amount of credit for testing it before me and then walking me through how to get to that point.

File: p5.js-web-editor.code-workspace [hunk 1]
```diff
@@ -0,0 +1,8 @@
+{
+	"folders": [
+		{
+			"path": "."
+		}
+	],
+	"settings": {}
+}
```
Comment (raclim) [inline p5.js-web-editor.code-workspace]: Could you remove this file? I think this might've been accidentally added in!

File: translations/locales/en-US/translations.json [hunk 2]
```diff
@@ -475,10 +475,10 @@
     "LinkMessage": "There was a problem linking your {{serviceauth}} account to your p5.js Web Editor account. Your {{serviceauth}} account has already been linked to another p5.js Web Editor account."
   },
   "ShareModal": {
-    "Embed": "Embed",
+    "Embed": "Embed sketch",
     "Present": "Present",
-    "Fullscreen": "Fullscreen",
-    "Edit": "Edit"
+    "Fullscreen": "Share sketch as view-only",
+    "Edit": "Share sketch and allow editing"
```
Comment (raclim) [inline translations/locales/en-US/translations.json]: This is looking great! This is a really minor change, but could we use Title Case capitalization for these?

**Review by raclim — CHANGES_REQUESTED** [review]
Thanks so much for your teamwork on this @team-epk and @freag! 

I'll add in a screenshot below just to show what it currently looks like: 
Screenshot 2025-08-22 at 12 16 26 PM

I think this looks overall pretty good! I added in some minor requested changes above—please let me know if you have any questions about them or need any assistance!

**Comment by raclim** [comment]
Hey @team-epk! Just wanted to check-in here! Let me know if you'd like any assistance with implementing any of the suggested changes!

**Comment by team-epk** [comment]
@raclim I just made the changes while you were typing, I think! Do I need to rebase the `share-modal` branch with my local one I made the changes to? I'm following the "preparing a pull request" document, which I think is geared towards a new request, not editing an existing one.

(Edited to add: now I see a commit note above this one, so maybe I did it at least sort of correctly?)

**Comment by raclim** [comment]
> @raclim I just made the changes while you were typing, I think! Do I need to rebase the share-modal branch with my local one I made the changes to? I'm following the "preparing a pull request" document, which I think is geared towards a new request, not editing an existing one.

Thanks for the quick update on this! The new committed changes look great! 

Yes, you will have to update the `share-modal` branch with the changes you just made! Looking into your repo, it seems like your latest changes are in the branch, [`share-modal-backup-aug-26-2025`](https://github.com/team-epk/p5.js-web-editor/tree/share-modal-backup-aug-26-2025), while this PR is based on the branch [`share-modal`](https://github.com/team-epk/p5.js-web-editor/tree/share-modal). 

I think either you can update `share-modal` with the changes you just made, or you can create a new PR based on the `share-modal-backup-aug-26-2025` branch!

> (Edited to add: now I see a commit note above this one, so maybe I did it at least sort of correctly?)

Yes, it's on its way there! The commit is being shown here since it references this pull request number!

**Comment by team-epk** [comment]
@raclim I think I did it this time? If nothing else, I gave myself The Vapors™, but I think I also added the right branch with the right files, after a few frightening errors from git.

**Review by raclim — DISMISSED** [review]

**Review by raclim — DISMISSED** [review]
Awesome, fortunately I think it seems like it worked! 😁 Thanks so much again for picking this up! Feel free to raise or take on any other issues that you'd be interested in!
