### PR TITLE
Fix screen reader features

### LINKED ISSUE #2188: Turning on accessible canvas settings causes sketches to break
#### Details about the bug:

- p5.js version: 1.6.0
- Web browser and version: Firefox 111.0.1 (also reported from another user on Chrome)
- Operating System: MacOS 12.5.1
- Steps to reproduce this:

Example sketch:
```js
function setup() {
  createCanvas(400, 400);
}

function draw() {
  background('red');
}
```
 
Then check this box in settings:
image

While normally this would just make a red canvas, with that setting turned on, we just get an error:
image

The error is coming from the p5.accessibility library editing the behaviour of colour functions:
image

Looking at the repo here https://github.com/processing/p5.accessibility it seems like it's no longer maintained. Is there an alternative that can be used? In the mean time, it seems to be broken.

### PR DESCRIPTION
**Pull request by nickmcintyre**
Fixes #2188

Changes:

I modified the `injectLocalFiles()` function in `client/Preview/EmbedFrame.jsx` to use `textOutput()` and `gridOutput()`.

I have verified that this pull request:

* [x] has no linting errors (`npm run lint`)
* [x] has no test errors (`npm run test`)
* [x] is from a uniquely-named feature branch and is up to date with the  `develop` branch.
* [x] is descriptively named and links to an issue number, i.e. `Fixes #123`

### CODE REVIEW

**Comment by nickmcintyre** [comment]
@raclim @Qianqianye @davepagurek @lindapaiste what do y'all think about this approach?

File: client/modules/Preview/EmbedFrame.jsx [hunk 1]
```diff
@@ -224,27 +224,23 @@ function injectLocalFiles(files, htmlFile, options) {
...
-      sketchDoc.getElementById('accessible-outputs').appendChild(gridSection);
+      gridCode = 'if (!this._accessibleOutputs.grid) this.gridOutput();';
     }
+    const fxn = `p5.prototype.ensureAccessibleCanvas = function _ensureAccessibleCanvas() {
+  ${textCode}
+  ${gridCode}
+};
+p5.prototype.registerMethod('afterSetup', p5.prototype.ensureAccessibleCanvas);`;
+    scriptElement.innerHTML = fxn;
+    sketchDoc.head.appendChild(scriptElement);
```
Comment (davepagurek) [inline client/modules/Preview/EmbedFrame.jsx:243]: Do you think there's any harm in putting this at the end of the body in case people rearrange the imports of their sketch and import p5 in the body too?

**Review by davepagurek — COMMENTED** [review]
Thanks for taking this on! I think this looks good, I just have one question (maybe for @lindapaiste?) about script tag order to try to handle as many cases as possible.

File: client/modules/Preview/EmbedFrame.jsx (hunk 1 above)
Comment (lindapaiste) [reply client/modules/Preview/EmbedFrame.jsx:243]: I think we're still not supporting importing p5 in the `body` 😭.  We implemented a fix to support it but then we rolled it back because it caused a major issue with the editor console.

issue: https://github.com/processing/p5.js-web-editor/issues/2327
reverted fix: https://github.com/processing/p5.js-web-editor/pull/2426
bug caused by fix: https://github.com/processing/p5.js-web-editor/issues/2518
reversion: https://github.com/processing/p5.js-web-editor/pull/2547

Comment (davepagurek) [reply client/modules/Preview/EmbedFrame.jsx:243]: got it, I think this is good to go then!

**Review by davepagurek — APPROVED** [review]

**Comment by nickmcintyre** [comment]
@lindapaiste @davepagurek just checking in. Can I help to improve this pull request? Also curious to hear your thoughts on #2702 which would be affected.

**Review by raclim — APPROVED** [review]
Thanks for working on this and for everyone's input here! Since it's already received a review, I'm going to merge this in!
