### PR TITLE
Nityam/fix private assets authorization

### LINKED ISSUE #3904: Private project assets exposed without authorization check
### p5.js version

latest

### What is your operating system?

Mac OS

### Web browser and version

all

### Actual Behavior

`getProjectAsset()` serves project assets (files, images) for any project ID without checking `visibility`. Anyone who knows or guesses a project ID can access **Private** project assets. Project listing correctly filters by visibility; this endpoint does not.

**Location:** `server/controllers/project.controller.js` lines 104–137

**Vulnerable routes:** `/full/:project_id/*`, `/embed/:project_id/*`, `/:username/sketches/:project_id/*`, `/present/:project_id/*`

### Expected Behavior

Private project assets should be served only to the project owner (or not at all for unauthenticated users). Public projects may be served to anyone.

### Steps to reproduce

1. Create a project and set visibility to **Private**.
2. Add an asset (e.g. image) to the project.
3. While logged out (or as another user), open the asset URL: e.g. `https://editor.p5js.org/full/<project_id>/<asset_path>`.
4. Observe that the private asset is returned (200) instead of 403.

## Snippet:

```js
// server/controllers/project.controller.js - getProjectAsset()
// Currently no visibility check before serving:
const project = await Project.findOne({ $or: [{ _id: projectId }, { slug: projectId }] })...
// ... then directly serves resolvedFile.content or fetches resolvedFile.url
```

### PR DESCRIPTION
**Pull request by Nixxx19**
### Issue:
Fixes #3904

The `getProjectAsset()` endpoint was serving project assets (files, images) for any project ID without checking the project's `visibility` setting. This security vulnerability allowed anyone who knew or guessed a project ID to access **Private** project assets, even when logged out or as a different user. While project listings correctly filter by visibility, this endpoint did not enforce the same authorization checks.

### Changes:

**Added authorization check to `getProjectAsset()`:**
- Added visibility and ownership validation before serving assets
- Private projects are now only accessible to their owners
- Unauthenticated users are blocked from accessing private project assets (returns 403)
- Non-owners are blocked from accessing private project assets (returns 403)
- Public projects remain accessible to everyone (no breaking changes)

**Security improvements:**
- Prevents unauthorized access to private project assets
- Protects all vulnerable routes: `/full/:project_id/*`, `/embed/:project_id/*`, `/:username/sketches/:project_id/*`, `/present/:project_id/*`
- Uses proper ObjectId comparison for ownership verification
- Follows the same authorization pattern as other protected endpoints in the codebase

**Added comprehensive test coverage:**
- Created test suite with 8 test cases covering all scenarios
- Tests verify: unauthenticated access blocking, non-owner blocking, owner access, public project access, and error handling
- All tests pass successfully

**Files changed:**
- `server/controllers/project.controller.js`: Added visibility and ownership check to `getProjectAsset` function
- `server/controllers/project.controller/__test__/getProjectAsset.test.js`: Added comprehensive test suite

### I have verified that this pull request:

* [x] has no linting errors (`npm run lint`)
* [x] has no test errors (`npm run test`)
* [x] has no typecheck errors (`npm run typecheck`)
* [x] is from a uniquely-named feature branch and is up to date with the `develop` branch.
* [x] is descriptively named and links to an issue number, i.e. `Fixes #3904`
* [x] meets the standards outlined in the [accessibility guidelines](https://github.com/processing/p5.js-web-editor/blob/develop/contributor_docs/accessibility.md)

### CODE REVIEW

File: server/controllers/project.controller.js [hunk 1]
```diff
@@ -131,6 +131,14 @@ export async function getProjectAsset(req, res) {
       .send({ message: 'Project with that id does not exist' });
   }
 
+  // Check visibility and ownership for private projects
```
Comment (raclim) [inline server/controllers/project.controller.js:134]: Hey! Just want to add in that this comment probably isn't needed here, since it can be inferred from the code!

**Review by raclim — APPROVED** [review]
Thanks so much for adding in the tests, this is an awesome start!

File: server/controllers/project.controller.js (hunk 1 above)
Comment (Nixxx19) [reply server/controllers/project.controller.js:134]: hey so sorry, i will remove this in next pr, thanks for flagging!!

**Comment by Nixxx19** [comment]
> Thanks so much for adding in the tests, this is an awesome start!

thank you!!

**Comment by ksen0** [comment]
Nice tests, thanks!

**Comment by Nixxx19** [comment]
> Nice tests, thanks!

thank you!!
