### PR TITLE
Move examples username and password to .env file

### LINKED ISSUE #555: Move examples username and password to .env file
#### Nature of issue?

- [X] Found a bug

#### Details about the bug: 

- Web browser and version:  N/A
- Operating System:  N/A
- Steps to reproduce this:

the file `server/examples.js` contains the p5 username and password. this should be moved to environment variables so that any user can't login to this account!

### PR DESCRIPTION
**Pull request by bharathvaj1995**
Fixes #555

### CODE REVIEW

File: server/examples.js [hunk 1]
```diff
@@ -289,15 +289,15 @@ function createProjectsInP5user(projectsInAllCategories) {
...
     if (err) throw err;
 
     let p5User = user;
     if (!p5User) {
       p5User = new User({
-        username: 'p5',
-        email: 'p5-examples@gmail.com',
-        password: 'test'
+        username: process.env.USER_NAME,
+				email: process.env.USER_EMAIL,
```
Comment (dhruvdutt) [inline server/examples.js]: Please clean extra indents.

Comment (bharathvaj1995) [reply server/examples.js]: ok
