### PR TITLE
Fix: Stream project ZIP download to prevent 502 timeout and memory issues #3780

### LINKED ISSUE #3780: Download project from editor not working
### p5.js version

any

### What is your operating system?

Mac OS

### Web browser and version

_No response_

### Actual Behavior

Project not being downloaded.

### Expected Behavior

Project downloads as zip file.

### Steps to reproduce

I want to be able to click download and download this project:
https://editor.p5js.org/.Fragmented_HF_ang./sketches/qbiGrxyps

### PR DESCRIPTION
**Pull request by Nixxx19**
Refactored the project download logic to use true end-to-end streaming, eliminating 502 Gateway Timeout errors for large projects (100+ files or >50MB) by preventing memory buffering and ensuring immediate response to gateways.

Fixes #3780

#### 1. **Replaced buffered ZIP generation with streaming**
- Changed from `generateAsync({ type: 'base64' })` to `generateNodeStream({ streamFiles: true })`
- Eliminated memory buffering - data flows directly from S3 → JSZip → Client
- Memory usage is now constant O(1) instead of O(n) where n = total project size

#### 2. **Sequential asset fetching to prevent connection storms**
- Replaced `Promise.all()` with sequential `for...of` loop
- Prevents opening 50+ parallel S3 connections
- Processes one file at a time to avoid memory spikes

#### 3. **Direct S3 streaming using AWS SDK**
- Integrated `@aws-sdk/client-s3` with `GetObjectCommand` for native S3 streaming
- Streams flow directly from S3 without intermediate buffering
- Replaced axios arraybuffer with stream responses

#### 4. **Gateway timeout prevention**
- Headers sent immediately with `Transfer-Encoding: chunked`
- Added keepalive mechanism (empty buffer writes every 1 second)
- First data bytes reach gateway within 1-2 seconds (previously 30-60s)

#### 5. **Runtime safety improvements**
- Added validation for missing `root` folder
- Graceful handling of missing `index.html`
- Prevention of duplicate external library entries
- Client disconnect detection and cleanup
- Proper stream error handling

#### 6. **Code quality**
- Removed unused imports
- Fixed ESLint errors (prefer-destructuring, no-await-in-loop)
- Added comprehensive JSDoc comments

### Technical Implementation

**Before (Buffered):**
```javascript
const base64 = await zip.generateAsync({ type: 'base64' });
const buff = Buffer.from(base64, 'base64');
res.end(buff);
```

**After (Streaming):**
```javascript
const zipStream = zip.generateNodeStream({
  type: 'nodebuffer',
  streamFiles: true,
  compression: 'DEFLATE'
});
zipStream.pipe(res);
```

**Memory Flow:**
```
S3 → Stream Handle → JSZip → Response Stream → Client
(No intermediate buffering)
```

---

I have verified that this pull request:

* [x] has no linting errors (`npm run lint`)
* [x] has no test errors (`npm run test`)
* [x] has no typecheck errors (`npm run typecheck`)
* [x] is from a uniquely-named feature branch and is up to date with the `develop` branch
* [x] is descriptively named and links to an issue number: `fix/download-project-streaming-zip-#3780`
* [x] meets the standards outlined in the [accessibility guidelines](https://github.com/processing/p5.js-web-editor/blob/develop/contributor_docs/accessibility.md)

### CODE REVIEW

**Comment by Nixxx19** [comment]
hi @raclim, sorry for the ping! 
i wanted to check in on this PR as it addresses a critical issue where large projects fail to download due to gateway timeouts during the zip buffering process. could you please take a look when you have a moment? thanks!

File: server/controllers/project.controller.js [hunk 1]
```diff
@@ -205,6 +218,11 @@ function bundleExternalLibs(project) {
     const path = src.split('/');
     const filename = path[path.length - 1];
 
+    // Prevent duplicate external libs if downloaded multiple times
```
Comment (raclim) [inline server/controllers/project.controller.js]: Could we remove some of the comments here in this file? We want to make sure comments only add any context that can't be gained from the code itself or by referencing past commits.

Comment (Nixxx19) [reply server/controllers/project.controller.js]: thanks for the feedback. i've stripped out the redundant comments and stuck to minimal jsdoc for params and returns. changes are pushed.

**Comment by Nixxx19** [comment]
hi @raclim, i've stripped out the redundant comments and stuck to minimal JSdoc for params and returns. changes are pushed. let me know what you think or if you’d like any further refinements.

**Comment by Nixxx19** [comment]
hi @raclim, i've stripped out the redundant comments and stuck to minimal JSdoc for params and returns. changes are pushed. let me know what you think or if you’d like any further refinements.

**Review by raclim — APPROVED** [review]
This looks great to me, thanks so much!
