### PR TITLE
fix: add email validation for google oauth

### LINKED ISSUE #3907: Google OAuth: missing email array validation
### p5.js version

_No response_

### What is your operating system?

None

### Web browser and version

_No response_

### Actual Behavior

Google strategy accesses `profile._json.emails[0]` without checking that `emails` exists and has length. If Google does not return emails, this throws `TypeError: Cannot read property '0' of undefined` and crashes the OAuth flow.

**Location:** `server/config/passport.js` Google Strategy, lines 244, 261, 265

### Expected Behavior

Before using `profile._json.emails[0]`, code should verify `profile._json?.emails` exists and has at least one element. If not, call `done(null, false, { msg: '...' })` instead of throwing.

### Steps to reproduce

1. Use (or mock) a Google OAuth profile that has no `emails` or empty `emails` array.
2. Complete Google sign-in so the strategy callback runs.
3. Observe unhandled TypeError and OAuth failure instead of a user-friendly message.

### Snippet:

```js
// passport.js - Google strategy
const existingUser = await User.findOne({
  google: profile._json.emails[0].value  // crashes if emails undefined
}).exec();
// ...
const primaryEmail = profile._json.emails[0].value;
// ...
req.user.google = profile._json.emails[0].value;
```

### PR DESCRIPTION
**Pull request by Nixxx19**
### Issue:
Fixes #3907

The Google OAuth strategy was accessing `profile._json.emails[0].value` without validating that the `emails` array exists or has any elements. This caused a `TypeError: Cannot read property '0' of undefined` crash when Google OAuth profiles didn't include email addresses, breaking the authentication flow.

### Changes:

**Added email validation helper function:**
- Created `getGooglePrimaryEmail()` helper function that safely extracts the primary email from Google OAuth profile
- Validates that `emails` array exists, is an array, and has at least one element
- Uses optional chaining for safe property access
- Trims whitespace from email addresses
- Returns `null` for missing or invalid emails

**Updated Google OAuth strategy callback:**
- Added validation at the start of the callback to check for email availability
- Returns user-friendly error message when emails are missing: "Unable to retrieve email from Google account. Please ensure your Google account has an email address and try again."
- Replaced all 6 unsafe `profile._json.emails[0].value` accesses with the validated `primaryEmail` variable
- Prevents crashes and provides graceful error handling

**Files changed:**
- `server/config/passport.js`: Added email validation helper and updated Google strategy

### I have verified that this pull request:

* [x] has no linting errors (`npm run lint`)
* [x] has no test errors (`npm run test`)
* [x] has no typecheck errors (`npm run typecheck`)
* [x] is from a uniquely-named feature branch and is up to date with the `develop` branch.
* [x] is descriptively named and links to an issue number, i.e. `Fixes #3907`
* [x] meets the standards outlined in the [accessibility guidelines](https://github.com/processing/p5.js-web-editor/blob/develop/contributor_docs/accessibility.md)

### CODE REVIEW

File: server/config/passport.js [hunk 1]
```diff
@@ -124,6 +124,22 @@ const getVerifiedEmails = (githubEmails) =>
 const getPrimaryEmail = (githubEmails) =>
   (lodash.find(githubEmails, { primary: true }) || {}).value;
 
+/**
+ * Get primary email from Google OAuth profile.
+ * Returns the first email if available, or null if emails array is missing/empty.
+ */
+const getGooglePrimaryEmail = (googleEmails) => {
+  if (
+    !googleEmails ||
```
Comment (clairep94) [inline server/config/passport.js]: I think this is already covered by `!Array.isArray(googleEmails)`, so is unnecessary

**Review by clairep94 — CHANGES_REQUESTED** [review]
looks great otherwise thanks!

File: server/config/passport.js (hunk 1 above)
Comment (Nixxx19) [reply server/config/passport.js]: true, sorry about that. fixed it now, thanks for flagging!

**Review by clairep94 — APPROVED** [review]

**Review by raclim — APPROVED** [review]
Thanks so much!
