### PR TITLE
2084 failing test in toolbarunittestjsx

### LINKED ISSUE #2084: Failing Test in Toolbar.unit.test.jsx
#### Details about the bug:

When tests are run using the command "npm run test:ci", regardless of the branch the user is in or the changes that have been made, one test regarding the Toolbar.unit.test.jsx file will fail.

### PR DESCRIPTION
**Pull request by raclim**
Fixes #issue-number

Changes:

I have verified that this pull request:

* [x] has no linting errors (`npm run lint`)
* [x] has no test errors (`npm run test`)
* [x] is from a uniquely-named feature branch and is up to date with the  `develop` branch.
* [x] is descriptively named and links to an issue number, i.e. `Fixes #123`

### CODE REVIEW

File: client/modules/IDE/components/Toolbar.jsx [hunk 1]
```diff
@@ -36,6 +37,17 @@ class Toolbar extends React.Component {
     this.setState({ projectNameInputValue: event.target.value });
   }
 
+  handleProjectNameClick() {
+    if (this.canEditProjectName) {
+      this.props.showEditProjectName();
+      setTimeout(() => {
+        if (this.projectNameInput) {
```
Comment (lindapaiste) [inline client/modules/IDE/components/Toolbar.jsx:44]: FYI, there is a newish feature in JavaScript which is a lifesaver when dealing with possibly undefined variables. It's called the [optional chaining operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining) - `?.`.  You can write `this.projectNameInput?.focus()` instead of an `if` statement.  When `this.projectNameInput` is `undefined` it will not call `focus()`.  I use `?.` all the time and I don't know how I lived without it!

Comment (raclim) [reply client/modules/IDE/components/Toolbar.jsx:44]: Thanks for the suggestion, I'll try updating it!
