### PR TITLE
Deepan190703/fix .mtl

### LINKED ISSUE #3067: Enable `.mtl` File Uploads
### Increasing Access

Allowing `.mtl` file uploads in the p5.js Web Editor would ensure feature consistency between the editor and p5.js itself, reducing potential confusion for users.

### Feature enhancement details

The p5.js Web Editor currently blocks the upload of `.mtl` files with a "you can't upload files of this type" error, despite `.mtl` file support being available in p5.js since version 1.9.2 (see processing/p5.js#6710). This discrepancy limits users' ability to fully utilize p5.js's 3D capabilities within the Web Editor.

image

### PR DESCRIPTION
**Pull request by deepan190703**
Fixes https://github.com/processing/p5.js-web-editor/issues/3067

Changes:
Allowing .mtl file uploads in the p5.js Web Editor would ensure feature consistency between the editor and p5.js itself, reducing potential confusion for users.

I have verified that this pull request:

 

- [x] has no linting errors (npm run lint)
- [x]  has no test errors (npm run test)
- [x]  is from a uniquely-named feature branch and is up to date with the develop branch.
- [x]  is descriptively named and links to an issue number, i.e. Fixes #3067

### CODE REVIEW

**Review by raclim — CHANGES_REQUESTED** [review]
Thanks for working on this! I think this looks pretty good so far! 

I think one additional change I would make is adding '.mtl' to where the different file formats are mentioned in the `translations/locales` files. Here's a screenshot of those files below, and I'm going to link the [specific line in the english translations](https://github.com/processing/p5.js-web-editor/blob/c4de2669ad4df5b0e99927a4dff8c7394d8f0744/translations/locales/en-US/translations.json#L252) for reference too. 
Screenshot 2024-03-27 at 7 25 27 PM

I think it should be fine as is, but I might also double check if the '.mtl' file needs a specific file mode besides 'text/plain' for the [`getFileMode()` function in the `Editor/index.js`](https://github.com/processing/p5.js-web-editor/blob/c4de2669ad4df5b0e99927a4dff8c7394d8f0744/client/modules/IDE/components/Editor/index.jsx#L329) file.

File: client/modules/IDE/components/Editor/index.jsx [hunk 1]
```diff
@@ -340,6 +340,8 @@ class Editor extends React.Component {
       mode = 'x-shader/x-fragment';
     } else if (fileName.match(/.+\.(vert|stl)$/i)) {
       mode = 'x-shader/x-vertex';
+    } else if (fileName.match(/.+\.mtl$/i)) {
```
Comment (raclim) [inline client/modules/IDE/components/Editor/index.jsx]: if we want .mtl files to have the 'x-shader/x-vertex' mode, I think it would be best to combine this with line 341 within the parentheses where `(vert|stl)` are (so maybe something like `(vert|stl|mtl)`), since the `x-shader/x-vertex' mode is already begin referenced there.

**Review by raclim — CHANGES_REQUESTED** [review]
Thank you for adding in the translations! 

I think besides the comment I left in the `index.js` file, it would be best to remove the changes in the `package.json` and `package-lock.json` file—ideally we don't want any changes to these files.

**Review by raclim — APPROVED** [review]
I added in one minor change that resets the `package-lock.json` file to mirror the one in the `main` branch, but overall I think this is great! Thanks for working on this and for your contribution!
