### PR TITLE
Authentication improvements - OAuth Login

### LINKED ISSUE #915: Link OAuth accounts from user settings page
#### Nature of issue?

- Existing feature enhancement

#### Details about the bug: 

- Web browser and version: Chrome
- Operating System: Chrome
- Steps to reproduce this bug:

#### Feature enhancement details:
As the user is already logged in, It makes no sense to display "Login with github" on the page.

### PR DESCRIPTION
**Pull request by catarak**
Fixes #915, Re: #1317

I discovered a bug with respect to email address duplications and OAuth login, so this PR addresses that, and cleans up the flow and language for linking social accounts from the Account Settings page.

I have verified that this pull request:

* [x] has no linting errors (`npm run lint`)
* [x] is from a uniquely-named feature branch and has been rebased on top of the latest master. (If I was asked to make more changes, I have made sure to rebase onto master then too)
* [x] is descriptively named and links to an issue number, i.e. `Fixes #123`

### CODE REVIEW

File: client/modules/User/components/SocialAuthButton.jsx [hunk 1]
```diff
@@ -31,22 +42,35 @@ const StyledButton = styled(Button)`
   width: ${remSize(300)};
 `;
 
-function SocialAuthButton({ service }) {
+function SocialAuthButton({ service, link, connected }) {
```
Comment (andrewn) [inline client/modules/User/components/SocialAuthButton.jsx]: I spent a while thinking _does `link` mean that this button's an `href`_? What is it linking _to_? Maybe it's just pre morning-coffee.

Perhaps instead of `link`, just the "connected" prop is enough to change the label type. If `connected` is null then display the login label otherwise display the `connect/connected` labels?

File: server/config/passport.js [hunk 2]
```diff
@@ -141,10 +152,9 @@ passport.use(new GoogleStrategy({
 
     User.findByEmail(primaryEmail, (findByEmailErr, existingEmailUser) => {
       let username = profile._json.emails[0].value.split('@')[0];
-      User.findByUsername(username, (findByUsernameErr, existingUsernameUser) => {
+      User.findByUsername(username, true, (findByUsernameErr, existingUsernameUser) => {
```
Comment (andrewn) [inline server/config/passport.js]: It's useful for the second parameter to be an `options` object e.g.

`User.findByUsername(username, { caseInsensitive: true }, () =>{ ... })`

- allows for future options
- provides a descriptions of what `true` means in this context
- matches the mongoose `find` method signatures

File: server/models/user.js [hunk 3]
```diff
@@ -187,15 +193,23 @@ userSchema.statics.findByUsername = function findByUsername(username, cb) {
...
  * @param {string} value - Email or username
+ * @param {boolean} caseInsensitive - Does a caseInsensitive query rather than
+ *                                    default query for username or email, defaults
+ *                                    to false
  * @callback [cb] - Optional error-first callback that passes User document
  * @return {Promise<Object>} - Returns Promise fulfilled by User document
  */
-userSchema.statics.findByEmailOrUsername = function findByEmailOrUsername(value, cb) {
+userSchema.statics.findByEmailOrUsername = function findByEmailOrUsername(value, caseInsensitive, cb) {
   const isEmail = value.indexOf('@') > -1;
```
Comment (andrewn) [inline server/models/user.js:208]: We [validate usernames not containing "@" chars in the client](https://github.com/processing/p5.js-web-editor/blob/7dbcde452b16df1d7d49c7bb83a9b630902e5846/client/utils/reduxFormUtils.js#L26) but I wonder whether this should also happen in the mongoose User model?

File: server/config/passport.js [hunk 4]
```diff
@@ -108,14 +113,20 @@ passport.use(new GitHubStrategy({
...
       } else {
-        const user = new User();
-        user.email = primaryEmail;
-        user.github = profile.id;
-        user.username = profile.username;
-        user.tokens.push({ kind: 'github', accessToken });
-        user.name = profile.displayName;
-        user.verified = User.EmailConfirmation.Verified;
-        user.save(saveErr => done(null, user));
+        let { username } = profile;
```
Comment (andrewn) [inline server/config/passport.js]: I'm a bit confused about when this flow will be triggered? If the user does not have an Editor account with the same email as their Github account?

File: client/modules/User/components/SocialAuthButton.jsx (hunk 1 above)
Comment (catarak) [reply client/modules/User/components/SocialAuthButton.jsx]: What I'm attempting to account for here is two different display options for the `SocialAuthButton`:
- One for the Login/Signup Page
- One for the Account Settings page, which uses the word "Link" rather than "Login". When the auth button is in "link" mode, it shows that a social account can either be "connected" or "not connected". 
So maybe this just needs to be changed to use better named variables?

File: server/config/passport.js (hunk 2 above)
Comment (catarak) [reply server/config/passport.js]: Good call 😄 I'll update this!

File: server/models/user.js (hunk 3 above)
Comment (catarak) [reply server/models/user.js:208]: Do you mean validating a username when saving a (new or existing) `User` document?

File: server/config/passport.js (hunk 4 above)
Comment (catarak) [reply server/config/passport.js]: It's expected that this would trigger when a user is registering for the Editor with a GitHub account, i.e. they clicked "Login with GitHub" from the Signup Page.

This just reminded me that I should test if linking social accounts works properly if the email they registered with for the Editor is different from the email for their GItHub/Google Account.

**Comment by catarak** [comment]
I tested creating an account with a different email from the social account the user wants to link, and it will link the social account to the registered account matching the social's email, not the account the user explicitly tried to link to. So that's a bug 😄

File: server/models/user.js (hunk 3 above)
Comment (andrewn) [reply server/models/user.js:208]: Yes! Just to ensure these username rules are respected at the core of the app.

**Comment by andrewn** [comment]
> I tested creating an account with a different email from the social account the user wants to link, and it will link the social account to the registered account matching the social's email, not the account the user explicitly tried to link to. So that's a bug 😄

Is there a way to write a test for this controller/passport functionality to help verify these different conditions? It's a bit tricky as it calls out to mongo quite a lot but it might be worth it?

**Comment by catarak** [comment]
> Is there a way to write a test for this controller/passport functionality to help verify these different conditions? It's a bit tricky as it calls out to mongo quite a lot but it might be worth it?

That's probably a good idea, I was testing this by having an open connection to the MongoDB (on mlab), then deleting the GitHub key and trying to re-link the account.

**Comment by catarak** [comment]
Hey @oruburos! I'd like to add some Spanish translations in this PR, and if you could help out, that would be great! Specifically with the following phrases:
- 'Connect GitHub Account'
- 'Re-link GitHub Account'
- 'Connect Google Account'
- 'Re-link Google Account'

Thank you!! If you'd prefer I'd not ask you for translations in the future let me know, I'm happy to ask other Spanish-speaking folks in the community.

**Comment by oruburos** [comment]
Hi @catarak, here are my suggestions

> * 'Connect GitHub Account'
'Conecta Cuenta Github'

> * 'Re-link GitHub Account'
'Vuelve a Vincular Cuenta Github'


> * 'Connect Google Account'
'Conecta con Cuenta Google'

> * 'Re-link Google Account'
'Vuelve a Vincular Cuenta Google '

**Comment by catarak** [comment]
@oruburos if you're up for it, I could use a few more translations:
- 'Unlink (GitHub/Google) Account'
- 'Error Linking Account'
- 'There was a problem linking your (GitHub/Google) account to your p5.js Web Editor account. Your (GitHub/Google) account has already been linked to another p5.js Web Editor account.'

Thank you for your help!

**Comment by oruburos** [comment]
@catarak Sure, here are my suggestions

> * 'Unlink (GitHub/Google) Account'
> * 'Desvincular Cuenta (Github/Google)'

> * 'Error Linking Account'
> * 'Error Vinculando Cuenta'

> * 'There was a problem linking your (GitHub/Google) account to your p5.js Web Editor account. Your (GitHub/Google) account has already been linked to another p5.js Web Editor account.'
> * 'Hubo un problema vinculando tu cuenta de (GitHub/Google) con tu cuenta del Editor Web p5.js.  Tu cuenta de (GitHub/Google) había sido vinculada previamente con otra cuenta del Editor Web p5.js.'

**Comment by montoyamoraga** [comment]
@catarak, i am going through the branches, i think this one is ready to be deleted :)
